name: Build TTMD Player Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission to Gradle
        run: chmod +x gradlew

      - name: Safely Swap Automotive Tag for Touchscreen
        run: find . -name "AndroidManifest.xml" -exec sed -i 's/android.hardware.type.automotive/android.hardware.touchscreen/g' {} +

      - name: Build Android App Bundle with Custom Suffix
        run: ./gradlew bundleAutoRelease -PAPP_ID_SFX=.ttmd

      - name: Upload Finished Bundle
        uses: actions/upload-artifact@v4
        with:
          name: TTMD-Player-Bundle
          path: '**/*.aab'
